name: Run PostgreSQL Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Wait for PostgreSQL
        run: |
          until pg_isready -h localhost -p 5432 -U postgres; do
            echo "Waiting for postgres..."
            sleep 2
          done
      - name: Execute SQL scripts
        run: |
          PGPASSWORD=postgres psql -h localhost -U postgres -d test_db -f 01_create_tables.sql
          PGPASSWORD=postgres psql -h localhost -U postgres -d test_db -f 02_insert_data.sql
          PGPASSWORD=postgres psql -h localhost -U postgres -d test_db -f 03_create_views.sql



      - name: Run tests
        run: pytest -v
